ecmwf/anemoi-training

CHANGELOG.md, src/anemoi/training/diagnostics/callbacks/__init__.py, src/anemoi/training/diagnostics/plots.py
Two minor errors in the callback plot functions produced errors when enabling the plots. This PR incorporates the fixes
- in the histogram plot a multiplication needs to be done out-of-place
- one call of self.plot was missing a variable
Plotting is now possible: [mlflow](https://mlflow.copernicus-climate.eu/#/experiments/81/runs/46b8f692bfb34888a60fe9019bb6ad26)
=> fix: minor errors in two callback plot functions

CHANGELOG.md, src/anemoi/training/diagnostics/mlflow/logger.py
The logger does its own serialisation of the config in `log_hyperparams`, which will trigger missing value errors if any optional config entries are still missing (such as wandb.entity).
This PR makes sure the config entry in the hyper parameters is serialisable without throwing missing value errors. Missing config entries will be resolved to a ??? string.
=> Fix hyperparameter logging crash with missing config values

CHANGELOG.md, pyproject.toml
Numpy is in v2 now and we're already getting the first problems. This pins the version <2 until we can confirm it works.
=> pin numpy <2 until tested

CHANGELOG.md, src/anemoi/training/data/dataset.py
Fix.
**Bug**
- In some cases, the self-implemented __len__ property on the NativeGridDataset Class does not return the same number of samples that would be equivalent to that implied by the per_worker_init
- In these cases this leads to things such as validation loop skipped, Hanging at end of a training epoch
**To Reproduce**
The example has the following setup:
- multiple GPU
- no limit on the training batches: `dataloader.limit_batches.training: null`
-> validation epoch is skipped.
- deleting the __len__ function solves this issue
Example of behaviour here: https://mlflow.copernicus-climate.eu/#/compare-runs?runs=%5B%22ab15907c4d5a45dd89a9c708eaea3dbf%22,%22dfb1bfa2d72e49769e28a5a138321006%22,%228731ff0d85bf40cbbe7f313fa22af005%22%5D&experiments=%5B%2281%22%5D
**Additional context** …
=> fix: remove len calculation in iterable dataset

.github/workflows/ci.yml, CHANGELOG.md
This is to limit the runs of downstream ci for pure documentation changes in all triggers using yaml aliases.
=> Define common paths ignore for downstream CI

CHANGELOG.md, src/anemoi/training/config/hardware/slurm.yaml
This provides an example how hydra can use environment variables to read from and provides SLURM batch job env variables to derive the correct number of GPUs and nodes.
=> Add a slurm hardware config

CHANGELOG.md, src/anemoi/training/diagnostics/callbacks/__init__.py
Current `AnemoiCheckpoint` allows to save the training and inference checkpoint with just one object by defining a custom `_save_checkpoint `method to handle this. However we also need to overwrite the `_remove_checkpoint` method to handle the removal of both training and inference checkpoint according to the settings defined in the eval_rollout.yaml config
**Please also include relevant motivation and context.**
PR is associated to this issue https://github.com/ecmwf-lab/aifs-mono/issues/257
Please delete options that are not relevant.
Ticket number  - 257
https://github.com/ecmwf-lab/aifs-mono/issues/257
You can @-tag people to review this PR in addition to formal review requests.
=> fix: saving frequency bug for inference checkpoints

CHANGELOG.md, tests/train/test_loss_scaling.py
Tests: remapped variables need to be dictionary
=> fix: remapped variables in tests need to be dictionaries

CHANGELOG.md, src/anemoi/training/utils/jsonify.py
This adds the conversion of a `datetime.timedelta` used for the frequency to a string for JSON serialisation.
Closes #42
=> Fix - `datetime.timedelta` to string conversion for JSON

CHANGELOG.md, docs/conf.py, docs/start/hydra-intro.rst, docs/start/training-your-first-model.rst, docs/user-guide/configuring.rst
After working through the documentation to get a simple training run going I encountered some issues with the docs.
This PR:
- fixes some broken links to the other anemoi repos
- updates some text on required overrides in the config
- updates the example config file with what's needed for a run (hopefully)
----
📚 Documentation preview 📚: https://anemoi-training--46.org.readthedocs.build/en/46/
=> Expanded intro docs and examples

CHANGELOG.md, src/anemoi/training/commands/train.py
This modifies the `sys.argv` to contain the subcommands as soon as it is passed to hydra.
=> [fix] Capture Anemoi Training subcommands in MLFlow

CHANGELOG.md, src/anemoi/training/diagnostics/mlflow/auth.py
During initial release QA, the `enabled` decorator in `TokenAuth` was turned into a staticmethod as a way to satisfy the linter, because it would complain about the argument not being named `self`.
This breaks the code in python 3.9, where static methods cannot be called from within the class. 
When running the login command on python 3.9:
```shell
Traceback (most recent call last):
File "./conda/envs/aifs-dev-py39/bin/anemoi-training", line 8, in <module>
sys.exit(main())
File "./anemoi-training/src/anemoi/training/__main__.py", line 23, in main
cli_main(__version__, __doc__, COMMANDS)
File "./conda/envs/aifs-dev-py39/lib/python3.9/site-packages/anemoi/utils/cli.py", line 135, in cli_main
cmd.run(args)
File "./anemoi-training/src/anemoi/training/commands/mlflow.py", line 79, in run
from …
```
=> Fix mlflow command on python 3.9

CHANGELOG.md, src/anemoi/training/commands/mlflow.py, src/anemoi/training/diagnostics/mlflow/__init__.py, src/anemoi/training/diagnostics/mlflow/logger.py, src/anemoi/training/diagnostics/mlflow/utils.py, src/anemoi/training/utils/mlflow_sync.py
Adds the `--authentication (-a)` option to the `mlflow sync` subcommand. This enables authentication on the destination server. It retrieves a token and sets it for the mlflow API to use during sync.
Tested the following: local logs -> new server, and old server -> new server (the latter only works from Atos).
Todo: test from Leonardo.
Usage:
`anemoi-training mlflow sync -s /path/to/logs -d https://mlflow.server -r 1234 -e sync-test -a`
=> Authentication support for mlflow sync

CHANGELOG.md, src/anemoi/training/diagnostics/mlflow/auth.py, tests/diagnostics/mlflow/test_auth.py
This implements the recent changes to the authentication layer for our mlflow server. 
We are no longer asking the user to enter their username/password in a bash prompt because this can be unsafe. Instead, we redirect the user to a webpage where they have to sign in with their ECMWF account and obtain a seed refresh token. The user then copy pastes this token into the prompt.
The rest of the flow remains the same. This manual copy paste action only needs to be done if the user has not logged in within 30 days, just like with the credentials before.
Also made the target env var an optional constructor argument, so it is more clear that this is where the token is stored during runtime.
=> New mlflow authentication API

CHANGELOG.md, pyproject.toml, src/anemoi/training/commands/train.py, src/anemoi/training/diagnostics/mlflow/logger.py
This is a proposed fix for interactive multi-GPU training, which is currently broken.
"interactive" in this context means: you call `anemoi-training train` directly in a shell.
Hydra expects full control over `sys.argv` , with `argv[0]` being the executable, and `argv[1:]` the hydra options.
This is incompatible with our subcommands, where `argv[0]` is `anemoi-training` and `argv[1]` is something like `train`. Hydra will try to ingest `train` as an option, and crash.
To get around this, we overwrite the argv so that `argv[0]` contains the executable and subcommand: `anemoi-training train`.
This makes hydra happy, and it works fine with 1 GPU.
For most training runs, we run training via Slurm. For this, we don't call the training command directly but we do `srun anemoi-training train` , …
=> Fix interactive multi-GPU training

CHANGELOG.md, src/anemoi/training/diagnostics/mlflow/client.py, tests/diagnostics/mlflow/test_client.py
closes #7 
Implements `AnemoiMlflowClient` that behaves like a regular `mlflow.MlflowClient`, but has the option to inject authentication calls before every mlflow function call. This is to support logging to our server from external codebases, they can import this logger. Authentication is turned off by default.
Usage:
```python
from anemoi.training.diagnostics.mlflow.client import AnemoiMlflowClient
client = AnemoiMlflowClient("http://localhost:5000", authentication=True)
client.search_experiments()
client.log_artifact(...)
```
There is also a `check_health` option that queries the health endpoint of the mlflow server on init. We also use this in the anemoi-training logger.
I default this to True because if it fails, it shows a more meaningful error rather than showing a failed HTML …
=> Add `AnemoiMlflowClient` with auth support

CHANGELOG.md, src/anemoi/training/config/dataloader/native_grid.yaml, src/anemoi/training/data/datamodule.py
Pinned memory caused crashes on our machine, so we need this setting to be configurable.
=> Make pin_memory of the Dataloader configurable

CHANGELOG.md, src/anemoi/training/diagnostics/callbacks/__init__.py, src/anemoi/training/diagnostics/mlflow/auth.py, src/anemoi/training/train/forecaster.py, src/anemoi/training/utils/masks.py
This PR adds an output_mask attribute to the GraphForecaster class. This enables rollout training for LAM models and simplifies the diagnostics plot to include only the limited area.
For global models, the previous behaviour is retained where the output_mask is all 1s.
=> Add output mask

CHANGELOG.md, docs/modules/diagnostics.rst, src/anemoi/training/config/config.yaml, src/anemoi/training/config/dataloader/native_grid.yaml, src/anemoi/training/config/diagnostics/callbacks/pretraining.yaml, src/anemoi/training/config/diagnostics/callbacks/rollout_eval.yaml, src/anemoi/training/config/diagnostics/evaluation.yaml, src/anemoi/training/config/diagnostics/plot/detailed.yaml, src/anemoi/training/data/datamodule.py, src/anemoi/training/diagnostics/callbacks/evaluation.py, src/anemoi/training/diagnostics/callbacks/plot.py, src/anemoi/training/train/forecaster.py
`RolloutEval` and `GraphForecaster` rollout code had diverged from an inital copy.
This PR refactors both to combine the rollout logic.
Closes #84 
----
📚 Documentation preview 📚: https://anemoi-training--87.org.readthedocs.build/en/87/
=> Refactor rollout

CHANGELOG.md, pyproject.toml
## Issue
`pyshtools` cannot be installed from pypi or conda for `3.13`
NOTE: Can be installed from source
Pin version to `<3.13`
- Temporary fix while pyshtools cannot be installed on 3.13
See https://github.com/SHTOOLS/SHTOOLS/issues/494 for more information
=> Lock python version to <3.13

CHANGELOG.md, src/anemoi/training/diagnostics/callbacks/__init__.py
LearningRateMonitor should be enabled automatically if tracking by mlflow or wandb is enabled. Right now there is a typo (mflow != mlflow) which means the learning rate is not tracked and therefore examination on mlflow is not possible. 
Possible reviewers: @HCookie
=> fix: enable learningrate monitor automatically

CHANGELOG.md, src/anemoi/training/config/graph/stretched_grid.yaml
**Description**
Adds a config file stretched_grid.yaml intended to be the default when training stretched grid models. 
- Intended to be used with a cutout dataset, and uses the StretchedTriNodes processor mesh with increased resolution over the limited area.
- Processor resolution 5 over the global and 8 over the limited area.
- 12 connections per processor node in the encoder and 3 conndections per input grid node in the decoder.
- Intended to be used with o96 global resolution and 10km limited area resolution for the input grid
Based on the setup used in https://arxiv.org/abs/2409.02891, but with lower resolution. Can be used with e.g. n320 + 2.5km by changing processor resolution to 7+10.
Sample graph using o96 and meps resampled to 10km is attached. …
=> Graph config for stretched grid graph

src/anemoi/training/diagnostics/logger.py
The old behavior when running offline with the default tracking uri ('???') would cause a crash. So now tracking uri isnt checked when running offline
```python
offline = config.diagnostics.log.mlflow.offline
if not offline:
tracking_uri = config.diagnostics.log.mlflow.tracking_uri
LOGGER.info("AnemoiMLFlow logging to %s", tracking_uri)
else:
tracking_uri = None
```
My understanding is there is no reason to check tracking uri when running offline because tracking_uri is provided later if the run is synced to mlflow. 
One use case for running offline without a tracking uri would be for external vendors benchmarking anemoi. They could use the mlflow offline logging to analyse GPU utilization etc.
=> dont check for tracking uri when running mlflow offline

CHANGELOG.md, src/anemoi/training/diagnostics/plots.py
Related to #126.
To plot the power spectra, we need to create a regular grid (n_pix_lat x n_pix_lon) and interpolate the data on it. The way n_pix_lat and n_pix_lon were previously defined is not robust and might lead to errors.
I am more or less confident that this change should fix the issue on n320 but not sure about LAM.
=> [FIX] Power spectra bug on n320 (LAM?)

src/anemoi/training/data/datamodule.py
Currently, the code uses an assertion to ensure that the validation dataset's start date occurs after the training dataset's end date. However, this check should issue a warning instead of being a blocking assertion.
=> Validation and Training dataset dates assertion

CHANGELOG.md, docs/user-guide/training.rst, src/anemoi/training/config/training/default.yaml, src/anemoi/training/train/forecaster.py
This is a PR to enable defining the warm-up period as part of the optimizer configuration. 
So far this value was hardcoded to '1000' but based on some tests we have done for the 'aifs v0.3' version, we could use smaller warm-up period for the operational finetuning stage.
----
📚 Documentation preview 📚: https://anemoi-training--155.org.readthedocs.build/en/155/
=> warmup config for reproducibility of aifs v0.3

CHANGELOG.md, src/anemoi/training/diagnostics/plots.py
Fix #163 
Instead of creating the plot for just one variable, it breaks when trying to iterate through the subplots.
List only one parameter for the histogram or spectrum plot
If only one variable is listed, create a list with only one entry.
=> Callback PlotHistogram breaks if only one variable is specified.

CHANGELOG.md, pyproject.toml, src/anemoi/training/config/graph/encoder_decoder_only.yaml, src/anemoi/training/config/graph/limited_area.yaml, src/anemoi/training/config/graph/multi_scale.yaml, src/anemoi/training/config/graph/stretched_grid.yaml, src/anemoi/training/diagnostics/callbacks/plot.py, src/anemoi/training/train/train.py
This PR updates the configuration files to align with the new recommended `anemoi-graphs` version (0.4.1). While the old configuration files are still supported in this release, they will be deprecated in a future version.  
**Action Required**: Please update your local configuration files to avoid future compatibility issues.
Tested on:
- 1 GPU: 
---
1. **Field Renaming**:  
- `edge_builder` has been renamed to `edge_builders`.  
- The new `edge_builders` field now accepts a **list of edge builders**.
2. **Masking Specification**:  
- The `source_mask_attr_name` and `target_mask_attr_name` fields are now defined **under each individual edge builder**.
=> Upgrade configs to anemoi-graphs 0.4.1

CHANGELOG.md, src/anemoi/training/data/dataset.py
We currently split dates between tasks / workers and then the shuffling is performed in these subsets. These changes shuffle the dataset consistently on all workers and then each worker takes its subset from the shuffled indices. 
Thx to @JoffreyDumontLeBrazidec for testing.
=> full shuffle of the dataset

CHANGELOG.md, src/anemoi/training/train/forecaster.py
Using the remapper without the imputer leads to an error as the code is trying to update the loss-function-scalar, which weights imputed NaN positions with zero. This updating should only take place if an imputer is used, otherwise, the weight-mask is of the wrong shape.
=> fix weight mask calculation when using the remapper and no imputer

CHANGELOG.md, src/anemoi/training/train/profiler.py
Fall back to an empty string if env vars arent found when writing the profiler report. Otherwise you would get an error right at the end of your job
=> [PROFILER] dont crash if an env var isnt found

src/anemoi/training/train/train.py
This small changeset fixes the `save_path` option:
- the `anemoi-graphs` package accepts `None`, see https://github.com/ecmwf/anemoi-graphs/blob/fc614171f45e757b14bac92188c4d0b785e41e46/src/anemoi/graphs/create.py#L183 
- the `anemoi-training` just passes a `None` setting from the hydra YAML now.
=> fix: allow None as graph save_path setting.

CHANGELOG.md, src/anemoi/training/diagnostics/callbacks/checkpoint.py
This PR would remove the saving of the metadata from the training checkpoint (it is still present in the inference ckpt). I am not sure if there is a reason we need it in both checkpoints?
This PR came out of the AIFSv03 training where we had quite a bit of pain restarting runs with the zip bug for checkpoints over a certain size. We had to use the work around `zip -d last.ckpt archive/anemoi-metadata/ai-models.json` many times, which this PR would get around. Very happy to be told we need this metadata in the training checkpoints! But if not this would avoid quite a bit of pain when resuming runs. 🙏
=> fix: remove saving of metadata for training ckpt

src/anemoi/training/train/train.py
Changed the model loading call when resuming without transfer learning and weights_only = True.
Closes #193
=> Fix for checkpoint loading.

src/anemoi/training/diagnostics/mlflow/logger.py
`metadata.dataset.specific.forward.forward.attrs.variables_metadata.` adds > 1000 params.
Add it to the list of metadata to be removed.
=> Remove excess metadata from variables

CHANGELOG.md, src/anemoi/training/data/datamodule.py, src/anemoi/training/data/dataset.py, src/anemoi/training/data/grid_indices.py, src/anemoi/training/diagnostics/callbacks/checkpoint.py, src/anemoi/training/train/forecaster.py, src/anemoi/training/train/train.py, src/anemoi/training/utils/masks.py, tests/diagnostics/test_checkpoint.py
We add to the checkpoint the latitudes, longitudes, and any other supporting bumpy arrays (e.g. masks)
=> Store numpy arrays in checkpoints

CHANGELOG.md, docs/modules/losses.rst, src/anemoi/training/config/training/default.yaml, src/anemoi/training/losses/utils.py, src/anemoi/training/losses/weightedloss.py, src/anemoi/training/train/forecaster.py, tests/train/test_scalar.py
Allow `all` to normalised and scaled when calculating the validation metrics.
Adds a config option to control which validation_metrics stay in normalised space and which scalars are applied.
```yaml
# List of validation metrics to keep in normalised space, and scalars to apply
scale_validation_metrics:
scalars_to_apply: ['variable']
metrics:
- 'all'
```
----
📚 Documentation preview 📚: https://anemoi-training--202.org.readthedocs.build/en/202/
=> Fix 'all' validation metrics
